const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test'),vm=require('node:vm');
const{Observable,shareReplay}=require('rxjs');
const source=fs.readFileSync(process.env.ADAPTER_SOURCE||path.resolve(__dirname,'../../../shared/bijux-docs/tooling/material/search-index-adapter.js'),'utf8');
const index=()=>({config:{lang:['en'],separator:'[\\s\\-]+'},docs:[{location:'platform/',title:'Platform',text:'resilient navigation',boost:3}]});
function fixture({href='https://example.invalid/bijux-core/',base='.',value='',focused=false,open=false}={}){
 let now=0,id=0;const timers=new Map(),requests=[],states=[],values=[],errors=[];const window=new EventTarget(),document=new EventTarget();const query={value,matches:selector=>selector==="[data-md-component='search-query']"},toggle={id:'__search',checked:open};document.activeElement=focused?query:{};document.querySelector=()=>query;document.getElementById=name=>name==='__config'?{textContent:JSON.stringify({base})}:name==='__search'?toggle:null;
 const handlers={window:new Map(),document:new Map()};for(const[owner,target]of Object.entries({window,document})){const add=target.addEventListener.bind(target),remove=target.removeEventListener.bind(target);target.addEventListener=(name,fn,...args)=>{if(!handlers[owner].has(name))handlers[owner].set(name,new Set());handlers[owner].get(name).add(fn);add(name,fn,...args)};target.removeEventListener=(name,fn,...args)=>{handlers[owner].get(name)?.delete(fn);remove(name,fn,...args)}}
 window.addEventListener('bijux:search-index-status',e=>states.push(JSON.parse(JSON.stringify(e.detail))));
 class Request{constructor(){this.aborted=false;requests.push(this)}open(method,url){this.method=method;this.url=url}send(){this.sent=true}abort(){this.aborted=true;this.onabort?.()}resolve(value){this.status=200;this.responseText=JSON.stringify(value);this.onload?.()}progress(loaded){this.onprogress?.({loaded})}fail(){this.onerror?.()}}
 const location={href,origin:new URL(href).origin};vm.runInNewContext(source,{window,document,CustomEvent,URL,XMLHttpRequest:Request,location,Date:{now:()=>now},setTimeout(fn,ms){timers.set(++id,{fn,at:now+ms,ms});return id},clearTimeout(id){timers.delete(id)}},{timeout:1000});
 const stream=window.bijuxSearchIndex.observe(()=>new Observable(()=>{throw Error('Native unabortable factory must not subscribe')}),shareReplay);
 const subscribe=()=>stream.subscribe({next:v=>values.push(JSON.parse(JSON.stringify(v))),error:e=>errors.push(e)});
 function event(name,target=query){const e=new Event(name);Object.defineProperty(e,'target',{value:target});document.dispatchEvent(e)}
 function advance(ms){const end=now+ms;while(true){let ready=[...timers].filter(([,t])=>t.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!ready)break;now=ready[1].at;timers.delete(ready[0]);ready[1].fn()}now=end}
 return{window,document,location,timers,requests,states,values,errors,handlers,subscribe,query,toggle,event,advance,jump(ms){now+=ms},retry(){window.dispatchEvent(new Event('bijux:search-index-retry'))},cancel(){window.dispatchEvent(new Event('bijux:search-index-cancel'))}};
}
function start(f){const s=f.subscribe();f.event('focusin');return s}
test('ordinary reading has no index request, no deadline timers, and unrelated input cannot start search',()=>{const f=fixture(),s=f.subscribe();f.advance(60000);assert.equal(f.requests.length,0);assert.equal(f.timers.size,0);f.event('input',{matches:()=>false});f.event('change',{id:'__search',checked:false});assert.equal(f.requests.length,0);s.unsubscribe()});
test('search focus/input/open establish one actual transfer without renewing hard deadline',()=>{for(const action of ['focusin','input','change']){const f=fixture(),s=f.subscribe();f.event(action,action==='change'?{id:'__search',checked:true}:f.query);assert.equal(f.requests.length,1);assert.equal(f.requests[0].timeout,45000);const hard=[...f.timers.values()].find(t=>t.ms===45000).at;f.advance(1000);f.event('focusin');f.event('input');f.retry();assert.equal(f.requests.length,1);assert.equal([...f.timers.values()].find(t=>t.ms===45000).at,hard);s.unsubscribe()}});
test('existing query, checked dialog, current focus and native q deep link start lazily admitted transfer',()=>{for(const options of [{value:'make'},{open:true},{focused:true},{href:'https://example.invalid/bijux-core/?q=make'},{href:'https://example.invalid/bijux-core/?q='}]){const f=fixture(options),s=f.subscribe();assert.equal(f.requests.length,1);s.unsubscribe()}});
test('shared native RxJS subscribers recover after fault and receive identical native config/docs/boost',()=>{const f=fixture(),a=f.subscribe(),b=f.subscribe();f.event('focusin');f.requests[0].fail();assert.equal(f.window.bijuxSearchIndex.state.reason,'network');assert.deepEqual(f.errors,[]);f.retry();const actual=index();f.requests[1].resolve(actual);assert.deepEqual(f.values,[actual,actual]);const c=f.subscribe();assert.equal(f.requests.length,2);assert.equal(f.values.length,3);f.retry();assert.equal(f.requests.length,2);a.unsubscribe();b.unsubscribe();c.unsubscribe()});
test('declared progressing transfer can exceed old8s deadline and complete below hard45s',()=>{const f=fixture(),s=start(f);for(let i=1;i<=3;i++){f.advance(6000);f.requests[0].progress(i*1000000)}assert.equal(f.requests[0].aborted,false);f.requests[0].resolve(index());assert.equal(f.window.bijuxSearchIndex.state.stage,'index-ready');assert.equal(f.values.length,1);assert.equal(f.timers.size,0);s.unsubscribe()});
test('zero-progress failure aborts at8s and remains explicitly retriable',()=>{const f=fixture(),s=start(f);f.advance(8000);assert.equal(f.requests[0].aborted,true);assert.equal(f.window.bijuxSearchIndex.state.reason,'stalled');f.event('input');assert.equal(f.requests.length,1);f.retry();f.requests[1].resolve(index());assert.equal(f.values.length,1);s.unsubscribe()});
test('repeated equal progress does not renew stall bound',()=>{const f=fixture(),s=start(f);f.advance(2000);f.requests[0].progress(10);for(let i=0;i<3;i++){f.advance(2000);f.requests[0].progress(10)}f.advance(2000);assert.equal(f.window.bijuxSearchIndex.state.reason,'stalled');s.unsubscribe()});
test('advancing bytes cannot renew total deadline beyond45s',()=>{const f=fixture(),s=start(f);for(let i=1;i<=8;i++){f.advance(5000);f.requests[0].progress(i)}f.advance(5000);assert.equal(f.window.bijuxSearchIndex.state.reason,'timeout');assert.equal(f.requests[0].aborted,true);assert.deepEqual(f.values,[]);s.unsubscribe()});
test('late success when timer dispatch is delayed still fails absolute operation age',()=>{const f=fixture(),s=start(f);f.jump(45001);f.requests[0].resolve(index());assert.equal(f.window.bijuxSearchIndex.state.reason,'timeout');assert.deepEqual(f.values,[]);s.unsubscribe()});
test('direct cancel aborts and excludes captured stale completion without restarting on focus',()=>{const f=fixture(),s=start(f);const stale=f.requests[0],late=stale.onload;f.cancel();assert.equal(stale.aborted,true);assert.equal(f.window.bijuxSearchIndex.state.reason,'cancelled');f.event('focusin');assert.equal(f.requests.length,1);f.retry();stale.status=200;stale.responseText=JSON.stringify(index());late();assert.deepEqual(f.values,[]);f.requests[1].resolve(index());assert.equal(f.values.length,1);s.unsubscribe()});
test('transport404, malformed payload and invalid document shape never deliver fabricated empty results',()=>{const f=fixture(),s=start(f);const first=f.requests[0];first.status=404;first.responseText='not found';first.onload();assert.equal(f.window.bijuxSearchIndex.state.reason,'network');f.retry();const second=f.requests[1];second.status=200;second.responseText='{broken';second.onload();assert.equal(f.window.bijuxSearchIndex.state.reason,'invalid-index');f.retry();f.requests[2].resolve({config:{},docs:[{location:42}]});assert.deepEqual(f.values,[]);assert.deepEqual(f.errors,[]);f.retry();f.requests[3].resolve({config:{lang:['en']},docs:[]});assert.equal(f.values.length,1);assert.equal(f.values[0].docs.length,0);s.unsubscribe()});
test('progress byte/NaN/regression and finalresponse capacity reject before native delivery',()=>{for(const loaded of [80*1024*1024+1,NaN,-1]){const f=fixture(),s=start(f);f.requests[0].progress(loaded);assert.equal(f.requests[0].aborted,true);assert.deepEqual(f.values,[]);s.unsubscribe()}const f=fixture(),s=start(f);const request=f.requests[0];request.status=200;request.responseText=' '.repeat(40*1024*1024+1);request.onload();assert.equal(f.window.bijuxSearchIndex.state.reason,'index-size');assert.deepEqual(f.values,[]);s.unsubscribe()});
test('same-origin index source is exact at deep route and external configured base is refused',()=>{const good=fixture({href:'https://example.invalid/bijux-core/deep/page/',base:'../..'}),a=start(good);assert.equal(good.requests[0].url,'https://example.invalid/bijux-core/search/search_index.json');a.unsubscribe();const bad=fixture({base:'https://other.invalid/site'}),b=start(bad);assert.equal(bad.requests.length,0);assert.equal(bad.window.bijuxSearchIndex.state.reason,'scope');b.unsubscribe()});
test('last native subscriber disposal aborts work/timers and all owned window/document handlers',()=>{const f=fixture(),a=f.subscribe(),b=f.subscribe();f.event('focusin');a.unsubscribe();assert.equal(f.requests[0].aborted,false);b.unsubscribe();assert.equal(f.requests[0].aborted,true);assert.equal(f.timers.size,0);for(const name of ['bijux:search-index-retry','bijux:search-index-cancel','pagehide','pageshow'])assert.equal(f.handlers.window.get(name).size,0);for(const name of ['focusin','input','change'])assert.equal(f.handlers.document.get(name).size,0);f.retry();f.event('input');assert.equal(f.requests.length,1)});
test('pagehide resumes only genuinely interrupted intended work; idle/cancelled/cached pages never refetch',()=>{for(const kind of ['idle','cancelled','cached','interrupted']){const f=fixture(),s=f.subscribe();if(kind!=='idle')f.event('focusin');if(kind==='cancelled')f.cancel();if(kind==='cached')f.requests[0].resolve(index());f.window.dispatchEvent(new Event('pagehide'));const restore=new Event('pageshow');Object.defineProperty(restore,'persisted',{value:true});f.window.dispatchEvent(restore);assert.equal(f.requests.length,kind==='interrupted'?2:kind==='idle'?0:1);s.unsubscribe()}});
test('synchronous loading-state disposal cannot leak a request or deadline timers',()=>{const f=fixture(),s=f.subscribe();f.window.addEventListener('bijux:search-index-status',e=>{if(e.detail.stage==='index-loading')s.unsubscribe()});f.event('focusin');assert.equal(f.requests.length,0);assert.equal(f.timers.size,0)});
test('synchronous loading-state cancel retires startup before any network send',()=>{const f=fixture(),s=f.subscribe();f.window.addEventListener('bijux:search-index-status',e=>{if(e.detail.stage==='index-loading')f.cancel()});f.event('focusin');assert.equal(f.requests.length,0);assert.equal(f.timers.size,0);assert.equal(f.window.bijuxSearchIndex.state.reason,'cancelled');s.unsubscribe()});
test('synchronous Retry during loading notification does not duplicate startup',()=>{const f=fixture(),s=f.subscribe();let once=false;f.window.addEventListener('bijux:search-index-status',e=>{if(e.detail.stage==='index-loading'&&!once){once=true;f.retry()}});f.event('focusin');assert.equal(f.requests.length,1);assert.equal([...f.timers.values()].filter(t=>t.ms===45000).length,1);f.requests[0].resolve(index());assert.equal(f.values.length,1);s.unsubscribe()});

test('cold shared native highlight links establish intent while an empty highlight does not',()=>{for(const suffix of ['?h=resilient+navigation','?q=']){const f=fixture({href:'https://example.invalid/bijux-core/'+suffix}),s=f.subscribe();assert.equal(f.requests.length,1);s.unsubscribe()}const empty=fixture({href:'https://example.invalid/bijux-core/?h='}),s=empty.subscribe();assert.equal(empty.requests.length,0);s.unsubscribe()});
test('instant document and history highlight intent starts one transfer without deadline renewal',()=>{const f=fixture(),s=f.subscribe();f.location.href='https://example.invalid/bijux-core/deep/?h=reader';f.window.dispatchEvent(new Event('bijux:search-location'));assert.equal(f.requests.length,1);f.advance(3000);f.window.dispatchEvent(new Event('popstate'));f.window.dispatchEvent(new Event('bijux:search-location'));assert.equal(f.requests.length,1);assert.ok([...f.timers.values()].some(t=>t.at===45000));s.unsubscribe();assert.equal(f.handlers.window.get('popstate').size,0);assert.equal(f.handlers.window.get('bijux:search-location').size,0)});
