const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test'),vm=require('node:vm');
const source=fs.readFileSync(process.env.RECOVERY_SOURCE||path.resolve(__dirname,'../../../shared/bijux-docs/scripts/search-recovery.js'),'utf8');
function fixture({hidden=false,inert=false}={}){const window=new EventTarget();let index={stage:'index-idle',attempt:0},worker={stage:'worker-loading',attempt:1};const document=new EventTarget();document.activeElement=null;const toggle={checked:true};document.getElementById=()=>toggle;class Element extends EventTarget{getClientRects(){return this.hidden?[]:[{}]}constructor(tag){super();this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.attrs=new Map();this.hidden=false;this.inert=false;this.disabled=false;this.className='';this.textContent=''}setAttribute(k,v){this.attrs.set(k,String(v))}getAttribute(k){return this.attrs.get(k)??null}append(...children){this.children.push(...children)}prepend(...children){this.children.unshift(...children)}contains(node){return this===node||this.children.some(c=>c.contains(node))}focus(){document.activeElement=this}querySelector(selector){const match=e=>selector==='button'?e.tagName==='BUTTON':selector==="[role='status']"?e.attrs.get('role')==='status':selector==='[data-bijux-index-cancel]'?e.dataset.bijuxIndexCancel==='true':selector.startsWith('.')?e.className.split(' ').includes(selector.slice(1)):false;for(const c of this.children){if(match(c))return c;const inner=c.querySelector(selector);if(inner)return inner}return null}}
 const output=new Element('div'),query=new Element('input'),results=new Element('div'),outside=new Element('button');results.className='md-search-result';results.hidden=hidden;results.inert=inert;output.append(results);document.activeElement=outside;document.createElement=tag=>new Element(tag);document.querySelector=s=>s==='.md-search__output'?output:s==="[data-md-component='search-query']"?query:null;window.bijuxSearchIndex={get state(){return index}};window.bijuxSearchWorker={get state(){return worker}};vm.runInNewContext(source,{window,document,Event,getComputedStyle:()=>({visibility:'visible'})},{timeout:1000});const controller=new AbortController();window.bijuxShell.searchRecovery.bind(controller.signal);const panel=output.querySelector('.bijux-search-recovery'),status=panel.querySelector("[role='status']"),retry=panel.querySelector('button'),cancel=panel.querySelector('[data-bijux-index-cancel]');return{window,document,panel,status,retry,cancel,results,query,outside,controller,toggle,set(i,w=worker){index=i;worker=w;window.dispatchEvent(new Event('bijux:search-index-status'))}}}
test('real index transfer exposes loading/cancel, disables Retry, and excludes old native results',()=>{const f=fixture();f.set({stage:'index-loading',attempt:1,received_bytes:10000});assert.equal(f.status.textContent,'Downloading search index…');assert.equal(f.panel.getAttribute('aria-busy'),'true');assert.equal(f.cancel.hidden,false);assert.equal(f.cancel.disabled,false);assert.equal(f.retry.disabled,true);assert.equal(f.results.hidden,true);assert.equal(f.results.inert,true);f.controller.abort()});
test('Cancel routes to owned transport, presents truthful canceled state and moves focus to enabled Retry',()=>{const f=fixture();f.set({stage:'index-loading',attempt:1});let cancels=0;f.window.addEventListener('bijux:search-index-cancel',()=>{cancels++;f.set({stage:'index-unavailable',attempt:2,reason:'cancelled'})});f.cancel.focus();f.cancel.dispatchEvent(new Event('click'));assert.equal(cancels,1);assert.match(f.status.textContent,/canceled/);assert.equal(f.cancel.hidden,true);assert.equal(f.retry.disabled,false);assert.equal(f.document.activeElement,f.retry);f.controller.abort()});
test('stalled and absolute transport timeout are visible without fabricated no-results',()=>{const f=fixture();for(const reason of ['stalled','timeout']){f.set({stage:'index-unavailable',attempt:1,reason});assert.match(f.status.textContent,reason==='stalled'?/stalled/:/timed out/);assert.equal(f.results.hidden,true);assert.equal(f.results.inert,true);assert.equal(f.panel.getAttribute('aria-busy'),'false');assert.equal(f.retry.disabled,false)}f.controller.abort()});
test('Retry dispatches only the applicable failed index/worker boundary',()=>{const f=fixture();let indexes=0,workers=0;f.window.addEventListener('bijux:search-index-retry',()=>indexes++);f.window.addEventListener('bijux:search-worker-retry',()=>workers++);f.set({stage:'index-unavailable',attempt:1,reason:'stalled'},{stage:'worker-loading',attempt:1});f.retry.dispatchEvent(new Event('click'));assert.equal(indexes,1);assert.equal(workers,0);f.set({stage:'index-ready',attempt:2},{stage:'worker-unavailable',attempt:1});f.retry.dispatchEvent(new Event('click'));assert.equal(indexes,1);assert.equal(workers,1);assert.equal(f.cancel.hidden,true);f.controller.abort()});
test('index-ready alone cannot reveal stale native results; latest worker result restores exact prior flags',()=>{const f=fixture({hidden:true,inert:false});f.set({stage:'index-ready',attempt:1},{stage:'worker-searching',attempt:1});assert.equal(f.results.inert,true);f.retry.focus();f.set({stage:'index-ready',attempt:1},{stage:'worker-ready',attempt:1});assert.equal(f.results.hidden,true);assert.equal(f.results.inert,false);assert.equal(f.panel.hidden,true);assert.equal(f.document.activeElement,f.query);f.controller.abort()});
test('readiness preserves reader focus outside recovery UI',()=>{const f=fixture();f.set({stage:'index-ready',attempt:1},{stage:'worker-ready',attempt:1});assert.equal(f.document.activeElement,f.outside);assert.equal(f.results.hidden,false);assert.equal(f.results.inert,false);f.controller.abort()});
test('document lifetime abort restores results and detaches cancel/retry handlers',()=>{const f=fixture();f.set({stage:'index-loading',attempt:1});let events=0;f.window.addEventListener('bijux:search-index-cancel',()=>events++);f.controller.abort();assert.equal(f.results.hidden,false);assert.equal(f.results.inert,false);f.cancel.dispatchEvent(new Event('click'));assert.equal(events,0);const text=f.status.textContent;f.set({stage:'index-unavailable',attempt:1,reason:'stalled'});assert.equal(f.status.textContent,text)});

function tab(f,shiftKey=false){const event=new Event('keydown',{cancelable:true});Object.defineProperty(event,'key',{value:'Tab'});Object.defineProperty(event,'shiftKey',{value:shiftKey});f.document.dispatchEvent(event);return event;}
test('native-header failed search exposes keyboard Retry without native Tab dismissal',()=>{const f=fixture();f.set({stage:'index-unavailable',attempt:1,reason:'network'});f.query.focus();assert.equal(tab(f).defaultPrevented,true);assert.equal(f.document.activeElement,f.retry);assert.equal(tab(f,true).defaultPrevented,true);assert.equal(f.document.activeElement,f.query);f.controller.abort()});
test('native-header busy search reaches Cancel and does not focus disabled Retry',()=>{const f=fixture();f.set({stage:'index-loading',attempt:1});f.query.focus();tab(f);assert.equal(f.document.activeElement,f.cancel);tab(f);assert.equal(f.document.activeElement,f.query);f.controller.abort()});
test('healthy, closed and disposed native search retain native keyboard behavior',()=>{const f=fixture();f.set({stage:'index-ready',attempt:1},{stage:'worker-ready',attempt:1});f.query.focus();assert.equal(tab(f).defaultPrevented,false);f.set({stage:'index-loading',attempt:2});f.toggle.checked=false;assert.equal(tab(f).defaultPrevented,false);f.toggle.checked=true;f.controller.abort();assert.equal(tab(f).defaultPrevented,false)});
