#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
import shlex
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[3]
SCRIPT_REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = SCRIPT_REPO_ROOT / ".github/standards/repo-config.manifest.json"
PROVENANCE_HEADER = (
    "# SSOT NOTICE: This file is generated by bijux-std standards sync.\n"
    "# Source of truth: bijux-std/.github/standards/repo-config.manifest.json and "
    "bijux-std/shared/bijux-gh/workflows/.\n"
    "# Do not edit this generated copy directly.\n\n"
)
REQUIRED_VERIFY_TRIGGER_PATHS = [
    ".bijux/**",
    ".github/**",
]
DEPENDABOT_PR_SKIP_CONDITION = (
    "github.event_name != 'pull_request' || "
    "github.event.pull_request.user.login != 'dependabot[bot]'"
)


def shared_github_source_root(repository_root: Path) -> Path:
    """Resolve managed GitHub sources in the standard or a synchronized consumer."""
    candidates = (
        repository_root / "shared/bijux-gh",
        repository_root / ".bijux/shared/bijux-gh",
    )
    for candidate in candidates:
        if candidate.is_dir():
            return candidate
    raise FileNotFoundError(
        "managed bijux-gh sources are missing from shared/ and .bijux/shared/"
    )


SHARED_GITHUB_ROOT = shared_github_source_root(SCRIPT_REPO_ROOT)
REQUIRED_STATUS_RULESET = SHARED_GITHUB_ROOT / "rulesets/main-branch-protection.json"
REQUIRED_STATUS_REFERENCE = SHARED_GITHUB_ROOT / "required-status-checks.md"


def repository_checkout_variable(repo_name: str) -> str:
    suffix = "".join(character.upper() if character.isalnum() else "_" for character in repo_name)
    return f"BIJUX_REPOSITORY_PATH_{suffix}"


def resolve_repository_checkout(repo_name: str) -> Path:
    variable = repository_checkout_variable(repo_name)
    configured_path = os.environ.get(variable)
    if configured_path:
        repo_path = Path(configured_path).expanduser().resolve()
    elif SCRIPT_REPO_ROOT.name == repo_name:
        repo_path = SCRIPT_REPO_ROOT
    else:
        repo_path = ROOT / repo_name

    if not repo_path.is_dir():
        raise FileNotFoundError(
            f"Repository checkout for '{repo_name}' not found at {repo_path}. "
            f"Set {variable} to its checkout path."
        )
    return repo_path


def yaml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if value is None:
        return "null"

    text = str(value)
    if re.fullmatch(r"[A-Za-z0-9_./:@-]+", text):
        return text
    escaped = text.replace('\\', '\\\\').replace('"', '\\"')
    return f'"{escaped}"'


def yaml_block_scalar(value: str, indent: int) -> list[str]:
    pad = " " * indent
    lines = [f"{pad}|"]
    for line in value.splitlines():
        lines.append(f"{pad}  {line}")
    if value.endswith("\n"):
        lines.append(f"{pad}")
    return lines


def dump_yaml(obj: Any, indent: int = 0) -> list[str]:
    pad = " " * indent
    lines: list[str] = []

    if isinstance(obj, dict):
        for key, value in obj.items():
            if value is None:
                lines.append(f"{pad}{key}:")
                continue
            if isinstance(value, (dict, list)):
                lines.append(f"{pad}{key}:")
                lines.extend(dump_yaml(value, indent + 2))
            elif isinstance(value, str) and "\n" in value:
                lines.append(f"{pad}{key}:")
                lines.extend(yaml_block_scalar(value, indent + 2))
            else:
                lines.append(f"{pad}{key}: {yaml_scalar(value)}")
        return lines

    if isinstance(obj, list):
        for item in obj:
            if isinstance(item, dict):
                lines.append(f"{pad}-")
                dict_lines = dump_yaml(item, indent + 2)
                if dict_lines:
                    first = dict_lines[0]
                    lines[-1] = f"{pad}- {first.strip()}"
                    lines.extend(dict_lines[1:])
            elif isinstance(item, list):
                lines.append(f"{pad}-")
                lines.extend(dump_yaml(item, indent + 2))
            else:
                lines.append(f"{pad}- {yaml_scalar(item)}")
        return lines

    lines.append(f"{pad}{yaml_scalar(obj)}")
    return lines


def render_release_env(entries: list[dict]) -> str:
    lines = ["# Unified release workflow configuration.", ""]
    for entry in entries:
        key = entry["key"]
        kind = entry["type"]
        value = entry["value"]

        if kind == "bool":
            rendered = "true" if value else "false"
        elif kind == "json":
            rendered = "'" + json.dumps(value, separators=(",", ":")) + "'"
        elif kind == "string":
            rendered = shlex.quote(str(value))
        else:
            raise ValueError(f"Unsupported release.env entry type: {kind}")

        lines.append(f"{key}={rendered}")

    lines.append("")
    return PROVENANCE_HEADER + "\n".join(lines)


def render_yaml_document(data: Any) -> str:
    return PROVENANCE_HEADER + "\n".join(dump_yaml(data)) + "\n"


def render_dependabot_document(data: Any) -> str:
    lines = dump_yaml(data)
    rendered: list[str] = []
    first_update = True

    for line in lines:
        if line.startswith("  - "):
            if not first_update:
                rendered.append("")
            first_update = False
        if line.startswith("    directory: /"):
            _, value = line.split(": ", maxsplit=1)
            line = f'    directory: "{value}"'
        rendered.append(line)

    return "\n".join(rendered) + "\n"


def additional_required_status_checks(repo: dict[str, Any]) -> list[dict[str, str]]:
    """Return validated repository-specific status check definitions."""
    checks = repo.get("additional_required_status_checks", [])
    if not isinstance(checks, list):
        raise ValueError("additional_required_status_checks must be a list")
    validated: list[dict[str, str]] = []
    seen: set[str] = set()
    for check in checks:
        if not isinstance(check, dict):
            raise ValueError("additional required status checks must be objects")
        context = check.get("context")
        workflow = check.get("workflow")
        if not isinstance(context, str) or not context.strip():
            raise ValueError("additional required status check context is required")
        if not isinstance(workflow, str) or not workflow.strip():
            raise ValueError("additional required status check workflow is required")
        if context in seen:
            raise ValueError(f"duplicate required status check context: {context}")
        seen.add(context)
        validated.append({"context": context, "workflow": workflow})
    return validated


def render_required_status_ruleset(repo: dict[str, Any]) -> str:
    """Render branch protection with repository-specific product gates."""
    ruleset = json.loads(REQUIRED_STATUS_RULESET.read_text(encoding="utf-8"))
    required_rule = next(
        rule for rule in ruleset["rules"] if rule["type"] == "required_status_checks"
    )
    configured = required_rule["parameters"]["required_status_checks"]
    existing = {check["context"] for check in configured}
    for check in additional_required_status_checks(repo):
        if check["context"] not in existing:
            configured.append({"context": check["context"]})
            existing.add(check["context"])
    return json.dumps(ruleset, indent=2) + "\n"


def render_required_status_reference(repo: dict[str, Any]) -> str:
    """Render human-readable status check ownership for one repository."""
    reference = REQUIRED_STATUS_REFERENCE.read_text(encoding="utf-8")
    checks = additional_required_status_checks(repo)
    if not checks:
        return reference
    details = ["Repository-specific required checks:", ""]
    details.extend(
        f"- `{check['context']}` (from workflow `{check['workflow']}`)"
        for check in checks
    )
    details.append("")
    return reference.replace("\nNotes:\n", "\n" + "\n".join(details) + "\nNotes:\n")


def normalize_labeler_rules(data: Any) -> Any:
    if not isinstance(data, dict):
        return data
    # actions/labeler supports these top-level config keys as scalars.
    option_keys = {"changed-files-labels-limit", "max-files-changed"}
    normalized: dict[str, Any] = {}
    for label, rules in data.items():
        if label in option_keys:
            normalized[label] = rules
            continue
        normalized[label] = rules if isinstance(rules, list) else [rules]
    return normalized


def validate_labeler_rules(data: Any) -> None:
    if not isinstance(data, dict):
        raise ValueError("labeler config must be a mapping")
    option_keys = {"changed-files-labels-limit", "max-files-changed"}
    for key, value in data.items():
        if key in option_keys:
            continue
        if not isinstance(value, list):
            raise ValueError(
                f"labeler config entry '{key}' must be a list of rule objects"
            )
        for index, item in enumerate(value):
            if not isinstance(item, dict):
                raise ValueError(
                    f"labeler config entry '{key}' item #{index + 1} must be a mapping"
                )


def find_repo_config(manifest: dict, repo_name: str) -> dict:
    for repo in manifest["repositories"]:
        if repo["name"] == repo_name:
            return repo
    raise KeyError(f"Repository '{repo_name}' not found in manifest")


def write_if_needed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def remove_if_generated(path: Path) -> None:
    if not path.exists():
        return
    content = path.read_text(encoding="utf-8")
    if content.startswith(PROVENANCE_HEADER):
        path.unlink()


def normalize_verify_trigger_paths(
    wrapper_definition: dict[str, Any],
) -> dict[str, Any]:
    on_section = wrapper_definition.get("on")
    if not isinstance(on_section, dict):
        return wrapper_definition

    for event_name in ("push", "pull_request"):
        event_definition = on_section.get(event_name)
        if not isinstance(event_definition, dict):
            continue

        raw_paths = event_definition.get("paths")
        if not isinstance(raw_paths, list):
            continue

        normalized_paths: list[str] = []
        seen_paths: set[str] = set()

        def add_path(path: str) -> None:
            if path in seen_paths:
                return
            seen_paths.add(path)
            normalized_paths.append(path)

        for required_path in REQUIRED_VERIFY_TRIGGER_PATHS:
            add_path(required_path)

        for raw_path in raw_paths:
            if not isinstance(raw_path, str):
                continue
            if raw_path.startswith(".github/") or raw_path.startswith(".bijux/"):
                continue
            add_path(raw_path)

        event_definition["paths"] = normalized_paths

    return wrapper_definition


def normalize_workflow_wrapper(
    wrapper_name: str,
    wrapper_definition: dict[str, Any],
) -> dict[str, Any]:
    if wrapper_name == "verify":
        return normalize_verify_trigger_paths(wrapper_definition)
    return wrapper_definition


def combine_job_if(existing: Any, condition: str) -> str:
    if not existing:
        return f"${{{{ {condition} }}}}"
    if not isinstance(existing, str):
        raise TypeError("job if condition must be a string when present")

    stripped = existing.strip()
    if stripped.startswith("${{") and stripped.endswith("}}"):
        stripped = stripped[3:-2].strip()
    return f"${{{{ ({condition}) && ({stripped}) }}}}"


def inject_dependabot_pull_request_skip(
    wrapper_name: str,
    wrapper_definition: dict[str, Any],
) -> dict[str, Any]:
    if wrapper_name != "ci":
        return wrapper_definition

    jobs = wrapper_definition.get("jobs")
    if not isinstance(jobs, dict):
        return wrapper_definition

    for job_definition in jobs.values():
        if not isinstance(job_definition, dict):
            continue
        job_definition["if"] = combine_job_if(
            job_definition.get("if"),
            DEPENDABOT_PR_SKIP_CONDITION,
        )

    return wrapper_definition


def render_repo(repo_name: str, manifest: dict) -> None:
    repo = find_repo_config(manifest, repo_name)
    repo_root = resolve_repository_checkout(repo_name)

    release_path = repo_root / ".github/release.env"
    release_content = render_release_env(repo.get("release_env", []))
    write_if_needed(release_path, release_content)

    write_if_needed(
        repo_root / ".github/rulesets/main-branch-protection.json",
        render_required_status_ruleset(repo),
    )
    write_if_needed(
        repo_root / ".github/required-status-checks.md",
        render_required_status_reference(repo),
    )

    dependabot_data = repo.get("dependabot")
    if dependabot_data is not None:
        dependabot_path = repo_root / ".github/dependabot.yml"
        dependabot_content = render_dependabot_document(dependabot_data)
        write_if_needed(dependabot_path, dependabot_content)

    labeler_data = repo.get("labeler")
    if labeler_data is not None:
        labeler_path = repo_root / ".github/labeler.yml"
        normalized_labeler = normalize_labeler_rules(labeler_data)
        validate_labeler_rules(normalized_labeler)
        labeler_content = render_yaml_document(normalized_labeler)
        write_if_needed(labeler_path, labeler_content)

    codecov_data = repo.get("codecov")
    if codecov_data is not None:
        codecov_path = repo_root / ".github/codecov.yml"
        codecov_content = render_yaml_document(codecov_data)
        write_if_needed(codecov_path, codecov_content)

    wrappers = repo.get("workflow_wrappers", {})
    wrapper_paths = {
        "ci": repo_root / ".github/workflows/ci.yml",
        "verify": repo_root / ".github/workflows/verify.yml",
    }
    for wrapper_name, wrapper_path in wrapper_paths.items():
        wrapper_definition = wrappers.get(wrapper_name)
        if wrapper_definition is None:
            remove_if_generated(wrapper_path)
            continue
        wrapper_definition = inject_dependabot_pull_request_skip(
            wrapper_name,
            wrapper_definition,
        )
        wrapper_definition = normalize_workflow_wrapper(
            wrapper_name,
            wrapper_definition,
        )
        write_if_needed(wrapper_path, render_yaml_document(wrapper_definition))


def main() -> None:
    parser = argparse.ArgumentParser(description="Render release.env, dependabot.yml, labeler.yml, codecov.yml, and workflow wrappers from manifest")
    parser.add_argument("--manifest", default=str(MANIFEST_PATH), help="Path to manifest JSON")
    parser.add_argument("--repo", action="append", default=[], help="Repository name (repeatable)")
    args = parser.parse_args()

    manifest = json.loads(Path(args.manifest).read_text(encoding="utf-8"))
    repos = args.repo or [repo["name"] for repo in manifest["repositories"]]

    for repo_name in repos:
        render_repo(repo_name, manifest)


if __name__ == "__main__":
    main()
